tare:
  name: Tare
  description: Zero the scale (tare)
  target:
    entity:
      integration: bookoo_ble
    device:
      integration: bookoo_ble
  fields: {}

start_timer:
  name: Start Timer
  description: Start the scale's built-in timer
  target:
    entity:
      integration: bookoo_ble
    device:
      integration: bookoo_ble
  fields: {}

stop_timer:
  name: Stop Timer
  description: Stop the scale's built-in timer
  target:
    entity:
      integration: bookoo_ble
    device:
      integration: bookoo_ble
  fields: {}

reset_timer:
  name: Reset Timer
  description: Reset the scale's timer to 00:00
  target:
    entity:
      integration: bookoo_ble
    device:
      integration: bookoo_ble
  fields: {}

tare_and_start_timer:
  name: Tare and Start Timer
  description: Zero the scale and start timer in one command
  target:
    entity:
      integration: bookoo_ble
    device:
      integration: bookoo_ble
  fields: {}

set_beep_level:
  name: Set Beep Level
  description: Set the beep volume level (0-5, 0 = silent)
  target:
    entity:
      integration: bookoo_ble
    device:
      integration: bookoo_ble
  fields:
    level:
      name: Level
      description: Beep volume level (0-5)
      required: true
      example: 3
      selector:
        number:
          min: 0
          max: 5
          mode: slider

set_auto_off:
  name: Set Auto-off Timer
  description: Set the auto-off duration in minutes (1-30)
  target:
    entity:
      integration: bookoo_ble
    device:
      integration: bookoo_ble
  fields:
    minutes:
      name: Minutes
      description: Auto-off duration in minutes (1-30)
      required: true
      example: 10
      selector:
        number:
          min: 1
          max: 30
          step: 1
          mode: slider # or box
          unit_of_measurement: minutes

set_flow_smoothing:
  name: Set Flow Smoothing
  description: Enable or disable flow rate smoothing
  target:
    entity:
      integration: bookoo_ble
    device:
      integration: bookoo_ble
  fields:
    enabled:
      name: Enabled
      description: Enable flow smoothing
      required: true
      example: true
      selector:
        boolean: